add gcr and missing dependencies
ubuntu/epiphany pull request #12
Opened 2023-10-13 15:31 UTC by jssotomdz

build was failing due to a missing gcr-4 dependency. Adding that uncovered some other missing dependencies and the need for a layout binding to handle webkitgtk

2023-10-13 18:50 UTC, kenvandine requested changes
Try not to hardcode arch paths

2023-10-13 18:50 UTC, kenvandine commented on snapcraft.yaml
> +  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
Please use $CRAFT_ARCH_TRIPLET here

2023-10-14 00:56 UTC, jssotomdz commented on snapcraft.yaml
> +  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
fixed! so used to only build for amd64

2023-10-14 03:34 UTC, kenvandine approved these changes
Thanks, looks good

2023-10-14 03:34 UTC, merged